
#Hikari Config (Used in Production)
#spring.datasource.hikari.pool-name=HikariCP
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.connection-timeout=10000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.validation-timeout=1800000
#spring.datasource.hikari.leak-detection-threshold=0
#spring.datasource.hikari.initialization-fail-timeout=-1

